version: "2"

networks:
  mynetwork:
    external:
      name: web

services:
  ccal:
    image: ufian/telegram
    restart: always
    command: python /src/ccal.py
    volumes:
    - .:/src
    networks:
      default: {}
      mynetwork:
        aliases:
        - udmurt`
